### PR TITLE
fix(codegen): skip vocabulary generation for system property names and add test - I97

### LINKED ISSUE #97: Vocabulary is auto generated for $identifier
## Bug Report 🐛
This issue may be considered a follow-up to [this](https://github.com/accordproject/concerto/issues/776) issue in the concerto repository.

Vocabulary is auto-generated for $identifier, while it is supposed to be skipped in this case.

## Expected Behavior
Should not auto generate vocabulary for $identifier

## Current Behavior
For this model,
``` namespace org.acme@1.0.0

concept Person identified {
	o String name
}

enum Color {
    o RED
    o BLUE
    o GREEN
}

asset Vehicle identified by vin {
    o String vin
    o Color color
}

asset Truck extends Vehicle {
    o Double weight
}
```
The following vocab is generated.
```
#Generated vocabulary for namespace: org.acme@1.0.0
locale: en
namespace: org.acme@1.0.0
declarations:
  - Person: Person
    properties:
      - $identifier: Identifier of the Person # should not be auto generated
      - name: Name of the Person
  - Color: Color
    properties:
      - RED: RED of the Color
      - BLUE: BLUE of the Color
      - GREEN: GREEN of the Color
  - Vehicle: Vehicle
    properties:
      - vin: Vin of the Vehicle
      - color: Color of the Vehicle
  - Truck: Truck
    properties:
      - weight: Weight of the Truck
```
## Possible Solution
Fix bug in vocabularyvisitor.js in the concerto-codegen repository.

## Steps to Reproduce

1. Run
```
concerto compile --target vocabulary
``` 
for the above .cto file.

### PR DESCRIPTION
**Pull request by apoorvsxna**
# Closes #97 

### Changes

-  Added condition to return null if propertyName is a reserved system property name.
-  Added unit test to verify that vocabulary is not generated for system property name ("$identifier"). 

### Related Issues
- [This](https://github.com/accordproject/concerto/issues/776) was the originally reported issue (in the [concerto](https://github.com/accordproject/concerto) repository).

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Merging to `main` from `fork:branchname`

### CODE REVIEW

File: lib/codegen/fromcto/vocabulary/vocabularyvisitor.js [hunk 1]
```diff
@@ -16,6 +16,7 @@
 
 const VocabularyManager  = require('@accordproject/concerto-vocabulary').VocabularyManager;
 const util = require('util');
+const ModelUtil = require('../../../../../concerto-core/lib/modelutil.js');
```
Comment (sanketshevkar) [inline lib/codegen/fromcto/vocabulary/vocabularyvisitor.js:19]: You might want to import it like this `const { ModelUtil } = require('@accordproject/concerto-core');`

File: lib/codegen/fromcto/vocabulary/vocabularyvisitor.js [hunk 2]
```diff
@@ -179,10 +180,16 @@ class VocabularyVisitor {
     visitProperty(property, parameters) {
         const declarationName = property.getParent().getName();
         const propertyName = property.getName();
+    
+        // Skip generating vocabulary for system property names
+        if (ModelUtil.isSystemProperty(propertyName) == true) {
```
Comment (sanketshevkar) [inline lib/codegen/fromcto/vocabulary/vocabularyvisitor.js:185]: ` if (ModelUtil.isSystemProperty(propertyName))` will also work.
Also any reason why `==` instead of `===` ?

File: test/codegen/fromcto/vocabulary/vocabularyvisitor.js [hunk 3]
```diff
@@ -464,4 +464,29 @@ describe('VocabularyVisitor', function () {
...
+
+    describe('visitProperty for Field', () => {
+        let param;
+        beforeEach(() => {
+            param = {
+                fileWriter: mockFileWriter
+            };
+        });
+        
+        it('should skip vocabulary generation for system property', () => {
```
Comment (sanketshevkar) [inline test/codegen/fromcto/vocabulary/vocabularyvisitor.js:476]: Please move the test [this ](https://github.com/accordproject/concerto-codegen/blob/f0b85700fea0c1092f76cd2a816251b074060863/test/codegen/fromcto/vocabulary/vocabularyvisitor.js#L369) test suite for fields.
We already have a test suite for `visitProperty for Field`

**Review by sanketshevkar — CHANGES_REQUESTED** [review]

File: test/codegen/fromcto/vocabulary/vocabularyvisitor.js (hunk 3 above)
Comment (apoorvsxna) [reply test/codegen/fromcto/vocabulary/vocabularyvisitor.js]: I modified both files accordingly. I believe it should be fixed now. Thanks for your patience.

**Review by sanketshevkar — APPROVED** [review]
Nice work @apoorvsxna!! Thanks for your contribution 💪

**Comment by sanketshevkar** [comment]
@mttrbrts can you please review the PR!

File: lib/codegen/fromcto/vocabulary/vocabularyvisitor.js [hunk 4]
```diff
@@ -179,10 +180,16 @@ class VocabularyVisitor {
...
         const propertyName = property.getName();
+    
+        // Skip generating vocabulary for system property names
+        if (ModelUtil.isSystemProperty(propertyName)) {
+            return null;
+        }
+    
         const propertyVocabulary = VocabularyManager.englishMissingTermGenerator(null, null, declarationName, propertyName);
-
+
```
Comment (jonathan-casey) [inline lib/codegen/fromcto/vocabulary/vocabularyvisitor.js:190]: pls cleanup tabs on newlines

Comment (apoorvsxna) [reply lib/codegen/fromcto/vocabulary/vocabularyvisitor.js]: Done. No more trailing spaces.

**Review by mttrbrts — APPROVED** [review]

**Comment by mttrbrts** [comment]
@apoorvsxna There's a test failure. Please fix, and then we can merge. Thanks.

```
  1) VocabularyVisitor
       visitProperty for Field
         should skip vocabulary generation for system property:
     TypeError: Attempted to wrap writeLine which is already wrapped
```

**Comment by apoorvsxna** [comment]
> @apoorvsxna There's a test failure. Please fix, and then we can merge. Thanks.
> 
> ```
>   1) VocabularyVisitor
>        visitProperty for Field
>          should skip vocabulary generation for system property:
>      TypeError: Attempted to wrap writeLine which is already wrapped
> ```

@mttrbrts. Fixed the failing test case. I think the issue should be resolved now.
