### PR TITLE
bug(common): include derived types in dependency graph

### LINKED ISSUE #56: Enhance graph.findConnectedGraph to use type hierarchy
Currently `graph.findConnectedGraph` does not use the type hierarchy, meaning that types that extend a target type are dropped from a filtered model.

## Context

Using the code below we can "tree shake" the model manager, to remove all types that are not connected to a root/target type, and then render the result as a PlantUML diagram. Although the output is correct, it is aggressive in that if we have a model containing derived types that *could* be used in place of an abstract type the derived types are removed, leaving only the abstract type.

```
if (process.argv.length > 2) {
    const graphVisitor = new Common.ConcertoGraphVisitor();
    const graph = new Common.DirectedGraph();
    mm.accept(graphVisitor, { graph });
    const connectedGraph = graph.findConnectedGraph(process.argv[2]);

    // now create a new model manager that only includes types
    // that are included in the dependency graph
    const filteredModelManager = mm.filter((declaration) =>
      connectedGraph.hasVertex(declaration.getFullyQualifiedName())
    );

    const visitor = new CodeGen.PlantUMLVisitor();
    const parameters = {
      fileWriter: new FileWriter("."),
      showCompositionRelationships: true,
      hideBaseModel: true,
    };
    filteredModelManager.accept(visitor, parameters);
  }
```

## Expected Behavior

It would be very useful to be able to optionally take into account the type hierarchy in the call to `graph.findConnectedGraph` allowing the caller to say "find everything connected to this type, and include all derived types that appear in the model".

## Actual Behavior

Derived types are removed as they are not directly connected in the graph.

## Steps to Reproduce
1. Run the REPL https://replit.com/@dselman/AccordProjectConcerto-Type-Dependencies#index.js
2. Note that the types `person@1.0.0.Dog` and `Cat` are not included, although the abstract type `Pet` which they extend **is**

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/concerto)
- [ ] [GitHub Issues](https://github.com/accordproject/concerto/issues)

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### PR DESCRIPTION
**Pull request by sanketshevkar**
# Closes #56 

### Changes

- While visiting classDeclarations, while adding super type as a dependency edge, we also add the supertype as a vertex and the classDeclaration as its dependent type so that we can include derived types of the super types in tree after we get the connected graph

### Flags

- <ONE>
- <TWO>

### Related Issues
- Issue #56 

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `main` from `fork:branchname`

### CODE REVIEW

File: test/common/graph.js [hunk 1]
```diff
@@ -55,81 +55,54 @@ describe('graph', function () {
...
    \`org.acme.hr.base@1.0.0.State\` --> \`concerto@1.0.0.Concept\`
-   \`org.acme.hr.base@1.0.0.TShirtSizeType\`
    \`org.acme.hr.base@1.0.0.TShirtSizeType\` --> \`concerto@1.0.0.Concept\`
-   \`org.acme.hr.base@1.0.0.EmployeeTShirtSizes\`
    \`org.acme.hr.base@1.0.0.EmployeeTShirtSizes\` --> \`org.acme.hr.base@1.0.0.SSN\`
    \`org.acme.hr.base@1.0.0.EmployeeTShirtSizes\` --> \`org.acme.hr.base@1.0.0.TShirtSizeType\`
-   \`org.acme.hr.base@1.0.0.Address\`
    \`org.acme.hr.base@1.0.0.Address\` --> \`concerto@1.0.0.Concept\`
    \`org.acme.hr.base@1.0.0.Address\` --> \`org.acme.hr.base@1.0.0.State\`
-   \`org.acme.hr.base@1.0.0.Time\`
```
Comment (mttrbrts) [inline test/common/graph.js:68]: We appear to have lost orphaned nodes in the graph. We should still write these (before tree-shaking).

**Review by mttrbrts — APPROVED** [review]
